#!/usr/bin/env python3
"""
fetch_home_dashboards.py — fetch all 9 home-page dashboards from
Salesforce and emit two artifacts:

  1. salesforce/flexipages/Getting_Started_Home.flexipage-meta.xml
     — a complete FlexiPage XML with a Tabs layout, one tab per
     dashboard, ready to deploy via Workbench / SF CLI.
  2. salesforce/package.xml
     — the deployment manifest.
  3. salesforce/DASHBOARD_REFERENCE.md
     — human-readable lookup of each dashboard's Id, DeveloperName,
     Title, Folder. Useful if the XML deploy fails and you fall
     back to UI clicks.

Run:
    cd ~/dealmatcher
    python3 tools/fetch_home_dashboards.py

Then deploy from ~/dealmatcher/salesforce/ — see salesforce/README.md.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path
from xml.sax.saxutils import escape

SCRIPT_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = SCRIPT_DIR / ".env.cheaphomesfla"
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))

try:
    from simple_salesforce import Salesforce
except ImportError:
    print("ERROR: simple_salesforce not installed. Run:")
    print("  python3 -m pip install --break-system-packages simple-salesforce")
    sys.exit(1)


# Dashboards we want on the home page, in the order they should appear
# as tabs. Edit this list to reorder, add, or remove dashboards from
# the layout — re-run the script and re-deploy.
WANTED_TITLES = [
    "01 Daily Lead Inflow",
    "02 Active Pipeline by Status",
    "03 Lead Source Performance",
    "04 Hot Buyers (CHF)",
    "09 Revenue This Month",
    "Marketing Dashboard",
    "KPI Dashboard",
    "Opportunities Dashboard",
]


def connect():
    return Salesforce(
        username=os.environ["SF_USERNAME"],
        password=os.environ["SF_PASSWORD"],
        security_token=os.environ["SF_SECURITY_TOKEN"],
    )


def fetch_dashboards(sf):
    # SOQL: filter to our 8 unique titles. Salesforce stores titles
    # case-sensitively; we use IN with the exact strings.
    titles_quoted = ", ".join(f"'{t}'" for t in WANTED_TITLES)
    soql = (
        f"SELECT Id, DeveloperName, Title, FolderName "
        f"FROM Dashboard "
        f"WHERE Title IN ({titles_quoted}) "
        f"ORDER BY Title"
    )
    result = sf.query(soql)
    return result["records"]


def make_flexipage_xml(dashboards):
    """Generate a FlexiPage XML in the EXACT format used by this org.

    Format reverse-engineered from a retrieve of the existing
    Getting_Started_Home FlexiPage:
      - Template: runtime_commerce_oci:homeTemplateOneRegion (one region)
      - Component for dashboards: desktopDashboards:embeddedDashboard
      - Properties: dashboardName (DeveloperName) + hideOnError=true
      - Layout: vertical stack of <itemInstances> inside one region.

    No tabs — this org's template doesn't support them.
    """
    item_instances_xml = []
    for i, d in enumerate(dashboards, 1):
        dev_name = d["DeveloperName"]
        identifier = "desktopDashboards_embeddedDashboard" if i == 1 else f"desktopDashboards_embeddedDashboard{i}"
        item_instances_xml.append(f"""        <itemInstances>
            <componentInstance>
                <componentInstanceProperties>
                    <name>dashboardName</name>
                    <value>{escape(dev_name)}</value>
                </componentInstanceProperties>
                <componentInstanceProperties>
                    <name>hideOnError</name>
                    <value>true</value>
                </componentInstanceProperties>
                <componentName>desktopDashboards:embeddedDashboard</componentName>
                <identifier>{identifier}</identifier>
            </componentInstance>
        </itemInstances>""")

    xml = f"""<?xml version="1.0" encoding="UTF-8"?>
<FlexiPage xmlns="http://soap.sforce.com/2006/04/metadata">
    <flexiPageRegions>
{chr(10).join(item_instances_xml)}
        <name>main</name>
        <type>Region</type>
    </flexiPageRegions>
    <masterLabel>Getting Started Home</masterLabel>
    <template>
        <name>runtime_commerce_oci:homeTemplateOneRegion</name>
    </template>
    <type>HomePage</type>
</FlexiPage>
"""
    return xml


PACKAGE_XML = """<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>Getting_Started_Home</members>
        <name>FlexiPage</name>
    </types>
    <version>60.0</version>
</Package>
"""


def make_dashboard_reference_md(dashboards):
    md = ["# Dashboard Reference — Home Page",
          "",
          "Auto-generated by `tools/fetch_home_dashboards.py`.",
          "",
          "If the XML deploy fails, use this lookup to add each dashboard manually via",
          "Setup → Lightning App Builder → Getting Started Home → Edit → click any '+'",
          "insertion point → click 'Dashboard' in left palette → type the exact name",
          "below into the right-panel dashboard dropdown → click match → Save.",
          "",
          "| # | Title | DeveloperName | Folder | Id |",
          "|---|---|---|---|---|"]
    for i, d in enumerate(dashboards, 1):
        md.append(f"| {i} | {d['Title']} | `{d['DeveloperName']}` | {d['FolderName']} | `{d['Id']}` |")
    md.append("")
    return "\n".join(md)


def main():
    print("Connecting to Salesforce...")
    sf = connect()
    print(f"  ✓ {sf.sf_instance}")

    print(f"Querying for {len(WANTED_TITLES)} home-page dashboards...")
    dashboards = fetch_dashboards(sf)
    print(f"  ✓ Found {len(dashboards)} dashboards:")
    for d in dashboards:
        print(f"    - {d['Title']} ({d['FolderName']})")

    if len(dashboards) < len(WANTED_TITLES):
        missing = set(WANTED_TITLES) - {d["Title"] for d in dashboards}
        print(f"  ⚠ Missing from query: {missing}")
        print("    Check titles are exact (case-sensitive). Continuing with what was found.")

    out_dir = SCRIPT_DIR / "salesforce"
    flexi_dir = out_dir / "flexipages"
    flexi_dir.mkdir(parents=True, exist_ok=True)

    xml = make_flexipage_xml(dashboards)
    xml_path = flexi_dir / "Getting_Started_Home.flexipage-meta.xml"
    xml_path.write_text(xml)
    print(f"\n  ✓ Wrote {xml_path.relative_to(SCRIPT_DIR)}")

    pkg_path = out_dir / "package.xml"
    pkg_path.write_text(PACKAGE_XML)
    print(f"  ✓ Wrote {pkg_path.relative_to(SCRIPT_DIR)}")

    ref_path = out_dir / "DASHBOARD_REFERENCE.md"
    ref_path.write_text(make_dashboard_reference_md(dashboards))
    print(f"  ✓ Wrote {ref_path.relative_to(SCRIPT_DIR)}")

    print("")
    print("Next: zip and deploy via Workbench. See salesforce/README.md.")
    print(f"  cd {SCRIPT_DIR}/salesforce")
    print("  zip -r home_page_deploy.zip package.xml flexipages/")
    print("")


if __name__ == "__main__":
    main()
